name: ACCELQ Github Action CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCELQ_APP_URL: ${{ vars.ACCELQ_APP_URL }}  # Using repository variable
      ACCELQ_USER_NAME: ${{ vars.ACCELQ_USER_NAME }}  # Using repository variable
      ACCELQ_API_KEY: ${{ secrets.ACCELQ_API_KEY }}  # Store this in GitHub Secrets
      ACCELQ_TENANT_CODE: ${{ vars.ACCELQ_TENANT_CODE }}  # Using repository variable
      ACCELQ_JOB_ID: "2968"

    steps:
    - name: Pull Docker Image
      run: |
        docker pull accelq/accelq-agent:latest

    - name: Generate Random Agent Name
      id: random-agent-name
      run: |
        RANDOM_NAME=$(echo "githubtest_$(openssl rand -hex 6)")
        echo "agent_name=${RANDOM_NAME}" >> $GITHUB_ENV

    - name: Run Docker Container
      run: |
        docker run -d \
        -e agent_name="${{ env.agent_name }}" \
        -e num_concurrent_jobs='1' \
        -e num_parallel_tc_per_job='1' \
        -e accelq_server_url="${{ env.ACCELQ_APP_URL }}" \
        -e user_id="${{ env.ACCELQ_USER_NAME }}" \
        -e api_key="${{ env.ACCELQ_API_KEY }}" \
        -e tenant_code="${{ env.ACCELQ_TENANT_CODE }}" \
        -e sharing_type='0' \
        -e agent_type='User' \
        accelq/accelq-agent:latest

    - name: Wait for 120 seconds
      run: sleep 120

    - name: ACCELQ Github-A Connect
      uses: accelq/accelq-ci-github-actions@v1.1
      with:
        appURL: "${{ env.ACCELQ_APP_URL }}"
        userName: "${{ env.ACCELQ_USER_NAME }}"
        apiKey: "${{ env.ACCELQ_API_KEY }}"
        tenantCode: "${{ env.ACCELQ_TENANT_CODE }}"
        jobId: "${{ env.ACCELQ_JOB_ID }}"
